---
kind: pipeline
name: test

steps:
  - name: check
    image: iamthefij/drone-pre-commit:personal

---
kind: pipeline
name: publish

depends_on:
  - test

trigger:
  event:
    - push
    - tag
  refs:
    - refs/heads/master
    - refs/tags/v*

steps:
  - name: submodules
    image: alpine/git
    commands:
      - git submodule init
      - git submodule update --recursive --remote

  - name: build
    image: golang:1.15
    commands:
      - apt-get update
      - apt-get install -y --no-install-recommends libpcsclite-dev
      # Download and install mage
      - (cd $GOPATH && go get -u -d github.com/magefile/mage)
      - (cd $GOPATH/src/github.com/magefile/mage && go run bootstrap.go)
      # Build distribution bundle
      - ./mage_fake_env.sh dist

  - name: gitea release
    image: plugins/gitea-release
    settings:
      title: ${DRONE_TAG}
      files: dist/*
      checksum:
        - md5
        - sha1
        - sha256
        - sha512
      base_url:
        from_secret: gitea_base_url
      api_key:
        from_secret: gitea_token
    when:
      event: tag

---
kind: pipeline
name: notify

depends_on:
  - test
  - publish

trigger:
  status:
    - failure

steps:

  - name: notify
    image: drillster/drone-email
    settings:
      host:
        from_secret: SMTP_HOST  # pragma: whitelist secret
      username:
        from_secret: SMTP_USER  # pragma: whitelist secret
      password:
        from_secret: SMTP_PASS  # pragma: whitelist secret
      from: drone@iamthefij.com
